# Generated by Django 4.2.6 on 2023-10-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Assets', 'Assets'), ('Consumable', 'Consumable'), ('Workforce Payment', 'Workforce Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforce')),
            ],
        ),
    ]
