# Generated by Django 4.2.6 on 2023-10-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workforce',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('adhar_card_no', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('skilled_or_non_skilled', models.CharField(choices=[('Skilled', 'Skilled'), ('Non-Skilled', 'Non-Skilled')], max_length=15)),
            ],
        ),
    ]
