# Generated by Django 4.2.6 on 2023-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('total_work', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_work', models.CharField(choices=[('KM', 'Kilometers'), ('M', 'Meters'), ('MI', 'Miles')], max_length=2)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
